### ISSUE TITLE
可以写一下斗鱼的吗？

### ISSUE THREAD

**Issue by m174460635** [linsongze/liveRedirect#3]
我自己照着real-url改了虎牙，但是斗鱼不知道怎么写了，因为我没写过go，对于在go里面如何处理字符串组，并且处理完成后用js执行那一块一头雾水。
能麻烦大佬写一下斗鱼的吗？

**Comment by linsongze** [comment]
点history..你会发现有斗鱼的，不过依赖了js的执行器，我给删除了。linux/mac部署的话应该可以用v8.。你把代码还原回来跑一下咯...

**Comment by linsongze** [comment]
已经把斗鱼的加回....

**Comment by m174460635** [comment]
我都在我的分支弄好了....

**Comment by m174460635** [comment]
对了,虎牙的也修了,支持一起看了
