### ISSUE TITLE
douyu返回域名的问题

### ISSUE THREAD

**Issue by ixinshang** [linsongze/liveRedirect#6]
使用国内以及国外的linux系统运行lr，解析斗鱼的线路的时候，反馈的域名`vplay3a.douyucdn.cn`，无法解析出来。
我看了一下`douyuLiveService.go`中的文件，反馈的应该`akm-tct`的域名，不知道能否修复一下。

**Comment by linsongze** [comment]
应该是二进制没更新，你用最新的二进制运行应该没问题。
